### ISSUE TITLE
Number is duplicated in Smart Search filter

### ISSUE THREAD

**Issue by Bagera** [zetkin/app.zetkin.org#1457] opened 2023-06-21 13:46 UTC
## Description

When making a phone banking filter the number of times a person has been called is duplicated.
Both the input and a text version of the number is visible at the same time.

## Steps to reproduce
1. Go to ['...'](http://app.dev.zetkin.org/organize/1/people/views/75)
2. Click "ellipsis" > Edit Smart Search Query
3. In the 4th filter you can see that it says "1 1 time"
4. Click the edit button for that row.
5. The text is "... 1 1 ...".

### Expected Behaviour

It should say "1 time"

### Actual Behaviour

It says "1 1 time" in overview and "1 1" in edit

## Screenshots (if you have any)
![image](https://github.com/zetkin/app.zetkin.org/assets/2950171/18147853-3cf4-4126-a646-dd287455ec25)

![image](https://github.com/zetkin/app.zetkin.org/assets/2950171/0dc3941f-309e-44c5-a090-1663deae14a1)

**Comment by richardolsson** [comment] 2023-06-21 13:53
Duplicate of #1448

**Closed by richardolsson** 2023-06-21 13:53 UTC
Labels: 🐜 bug
