### ISSUE TITLE
Tomorrow/Yesterday-messages for CAs, Surveys and Emails in the Activity list and Archive.

### ISSUE THREAD

**Issue by ziggabyte** [zetkin/app.zetkin.org#1742] opened 2024-01-11 09:33 UTC
## Description
In the Activity list: 
A user should be able to see a message in the activity list if a Call assignment and Survey ends or begins tomorrow, and if an Email is sent tomorrow. 
In the Archive:
A user should be able to see a message in the archive if an Email was sent yesterday.

## Estimated size (S, M, L)
S

I think this issue is size S because there is already a similar message on the Event list items, so that can be used as a guide for how to implement. 

## Requirements
- [ ] Message for Surveys in Activity list
- [ ] Message for Call assignments in Activity list
- [ ] Message for Emails in Activity list
- [ ] Message for Emails in Archive

## Design specifications
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/bb821f12-8cbc-48e9-b4e6-2d28c0aefc05)
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/b4d98452-665d-4bfa-bf59-84383303b941)
![bild](https://github.com/zetkin/app.zetkin.org/assets/58265097/1a2e42c3-3cb7-4c2a-9f7c-c7d96679aff3)

## Open questions
What is a good wording for emails? I don't think "sends tomorrow" is great.

**Comment by richardolsson** [comment] 2024-12-21 13:08
This is a duplicate of #2084.

**Closed by richardolsson** 2024-12-21 13:08 UTC
Labels: 🚪 entry-level, 🐟  Small
