### ISSUE TITLE
Fix the MISSING_TRANSLATION error

### ISSUE THREAD

**Issue by samuelskanberg** [zetkin/app.zetkin.org#114] opened 2021-04-10 10:17 UTC
To replicate:

```
sudo yarn devserver
```

Visit http://www.dev.zetkin.org

In the console the following appear:

```
{ Error: [@formatjs/intl Error MISSING_TRANSLATION] Missing message: "misc.publicHeader.login" for locale "en", using id as fallback. 

    at new MissingTranslationError (/home/samuel/code/zetkin/app.zetkin.org/node_modules/@formatjs/intl/src/error.js:63:28)
    at formatMessage (/home/samuel/code/zetkin/app.zetkin.org/node_modules/@formatjs/intl/src/message.js:65:21)
    at formatMessage (/home/samuel/code/zetkin/app.zetkin.org/node_modules/react-intl/src/components/provider.js:47:39)
    at /home/samuel/code/zetkin/app.zetkin.org/node_modules/react-intl/src/components/message.js:23:17
    at processChild (/home/samuel/code/zetkin/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/home/samuel/code/zetkin/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/samuel/code/zetkin/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/samuel/code/zetkin/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/home/samuel/code/zetkin/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/home/samuel/code/zetkin/app.zetkin.org/node_modules/next/dist/next-server/server/render.js:54:851)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:141:19)
    at loadGetInitialProps (/home/samuel/code/zetkin/app.zetkin.org/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/home/samuel/code/zetkin/app.zetkin.org/node_modules/next/dist/next-server/server/render.js:54:1142)
  code: 'MISSING_TRANSLATION',
  descriptor:
   { id: 'misc.publicHeader.login',
     description: undefined,
     defaultMessage: undefined } }
```

**Comment by richardolsson** [comment] 2021-04-20 14:05
Duplicate of #105

**Closed by richardolsson** 2021-04-20 14:05 UTC
