### ISSUE TITLE
Error when editing call assignment target group

### ISSUE THREAD

**Issue by niklasva82** [zetkin/app.zetkin.org#1560] opened 2023-09-26 23:20 UTC
## Description
When editing a call assignment target group, an error occurs.

## Steps to reproduce
1. Go to a call assignment
2. Click on Edit target group

### Expected Behaviour
A smart search dialog should be displayed.

### Actual Behaviour
The erros below occur instead.

## Screenshots (if you have any)
![Screenshot from 2023-09-27 01-15-03](https://github.com/zetkin/app.zetkin.org/assets/14962107/e4f308f5-f9ea-4b17-91e5-6bdd34425e74)
![Screenshot from 2023-09-27 01-15-08](https://github.com/zetkin/app.zetkin.org/assets/14962107/195d60a7-65ed-44f9-9f1c-5de791ac3f8f)

**Comment by richardolsson** [comment] 2023-09-28 03:55
This happens when there is a `limit` somewhere in a Smart Search query, but you're running a version of the app which does not yet support it. So it's not a bug as far as I can tell.

I'm closing as not a bug, but please reopen if you are able to reproduce it on the limit operator branch.

**Closed by richardolsson** 2023-09-28 03:55 UTC
Labels: 🐜 bug
