### ISSUE TITLE
Request fail on deleting a view

### ISSUE THREAD

**Issue by KraftKatten** [zetkin/app.zetkin.org#1208] opened 2023-04-07 13:49 UTC
## Description
This was found while working on #1201. There's a network call that fails after the view has been deleted, triggering a runtime error.

Note: Even with the fix for #1201, the error still occurs. Even if we try to navigate away before deleting the view, we still get this error.

## Steps to reproduce

1. Go to http://localhost:3000/organize/1/people
2. Click on "Create view" in top right, which will create and navigate to a new view
3. On the new view, click the "ellipsis menu" (⋮) in the top right
4. Click "Delete view"
5. Click "Confirm"

### Expected Behaviour
No error is shown. Javascript should work.

### Actual Behaviour
We get a runtime error and Javascript stops working.

## Screenshots (if you have any)
![bild](https://user-images.githubusercontent.com/21238654/230618661-17a7994e-3af1-4159-87db-1ddacff523f0.png)

**Comment by ziggabyte** [comment] 2024-04-09 15:07
Confirm that this is still a bug after the email feature has been merged to main

**Comment by henrycatalinismith** [comment] 2024-07-23 18:58
I'm logged in as testadmin and don't see a Create view button in the top right menu on http://localhost:3000/organize/1/people/duplicates.

<img width="222" src="https://github.com/user-attachments/assets/c036bb78-ce22-411b-a0a4-f29cdc4c162e" />

**Comment by richardolsson** [comment] 2024-07-23 19:17
"Views" were renamed to "Lists". So the equivalent is "Create list".

**Comment by henrycatalinismith** [comment] 2024-07-24 08:39
Lists is definitely a better user-facing name.

Been investigating this further. It's very spooky.

| console.log debugging | deleting a view |
|-|-|
|  ![Screenshot 2024-07-24 at 10 28 54](https://github.com/user-attachments/assets/01f3ed02-7de2-429d-b0ac-8cb5dec25e65) | ![2024-07-24 10 25 50](https://github.com/user-attachments/assets/bec8448e-db96-4288-8db8-cfd9a4f2bc5e) |

The console output there is filtered to only show stuff matching the view ID. The full output is as follows.

```
shouldLoad item 44 deleted=false
shouldLoad item /organize/1/people/lists/44 deleted=false
deleteView begin 44
shouldLoad item 44 deleted=false
shouldLoad item /organize/1/people/lists/44 deleted=false
viewDeleted store action begin 44
viewDeleted store action end 44
shouldLoad item 44 deleted=true
shouldLoad item /organize/1/people/lists/44 deleted=false
shouldLoad item 44 deleted=true
shouldLoad item /organize/1/people/lists/44 deleted=false
shouldLoad item 44 deleted=true
deleteView end 44
shouldLoad item /organize/1/people/lists/44 deleted=false
shouldLoad item 44 deleted=false
shouldLoad item /organize/1/people/lists/44 deleted=false
shouldLoad item 44 deleted=false
```

I see three problems here.

1. There seem to be two different remoteItem instances corresponding to list 44. One has an ID of `44` and the other has an ID of `/organize/1/people/lists/44`.
2. Only the remote item whose ID is `44` gets marked as deleted. The one whose ID is `/organize/1/people/lists/44` never gets marked as deleted. This is one potential cause of the error.
3. Shortly after the [`deleteView` callback](https://github.com/zetkin/app.zetkin.org/blob/main/src/features/views/layout/SingleViewLayout.tsx#L117-L130) finishes, the remote item whose ID is `44` reverts its deleted flag to a `false` value. This is another potential cause of the error.

Fun investigation. Will continue throwing a bit of time at it here and there when I can.

**Comment by henrycatalinismith** [comment] 2024-07-24 20:25
Cracked the root cause now. The `/organize/1/people/lists/44` remoteItem was unrelated (breadcrumbs). Deleting a view marks the viewList as stale. Marking the viewList as stale causes it to be fetched. The freshly fetched viewList doesn't contain an entry for the deleted view, but we're still on the view's page, where [`useView()`](https://github.com/zetkin/app.zetkin.org/blob/main/src/features/views/hooks/useView.ts) can only assume that this is a simple cache miss on a fresh page load, so it tries to fetch the deleted view and triggers the error.

**Comment by richardolsson** [comment] 2024-07-25 06:08
Your conclusion is correct @henrycatalinismith, and I'm sorry you had to redo this research. This problem has existed for several other data types and has been fixed elsewhere, so I'm sure this should be fixable as well.

I'm honestly a little bit surprised that the _list_ is marked as stale. The item should be marked as `deleted` (which is the new property we introduced to `RemoteItem` to fix this elsewhere), but I don't think the list should be marked as stale because we shouldn't have to refetch the list after marking the item as deleted. This is probably a remnant since before we had the `deleted` property.

Have a look at the `deleted` property and commits related to it historically to find fixes to other data types (e.g. events and emails).

**Closed** 2024-08-12 07:47 UTC
Labels: 🐜 bug
