### ISSUE TITLE
Fix the INVALID_CONFIG error message related to locate

### ISSUE THREAD

**Issue by samuelskanberg** [zetkin/app.zetkin.org#113] opened 2021-04-10 10:15 UTC
To replicate:

```
sudo yarn devserver
```

Visit http://www.dev.zetkin.org

In the console the following appear:

```
{ Error: [@formatjs/intl Error INVALID_CONFIG] "locale" was not configured, using "en" as fallback. See https://formatjs.io/docs/react-intl/api#intlshape for more details 

    at new InvalidConfigError (/home/samuel/code/zetkin/app.zetkin.org/node_modules/@formatjs/intl/src/error.js:37:23)
    at Object.createIntl (/home/samuel/code/zetkin/app.zetkin.org/node_modules/@formatjs/intl/src/create-intl.js:37:21)
    at Object.createIntl (/home/samuel/code/zetkin/app.zetkin.org/node_modules/react-intl/src/components/provider.js:63:27)
    at new IntlProvider (/home/samuel/code/zetkin/app.zetkin.org/node_modules/react-intl/src/components/provider.js:83:27)
    at processChild (/home/samuel/code/zetkin/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3305:14)
    at resolve (/home/samuel/code/zetkin/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/samuel/code/zetkin/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/samuel/code/zetkin/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/home/samuel/code/zetkin/app.zetkin.org/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/home/samuel/code/zetkin/app.zetkin.org/node_modules/next/dist/next-server/server/render.js:54:851)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:141:19)
    at loadGetInitialProps (/home/samuel/code/zetkin/app.zetkin.org/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/home/samuel/code/zetkin/app.zetkin.org/node_modules/next/dist/next-server/server/render.js:54:1142) code: 'INVALID_CONFIG' }

```

**Comment by richardolsson** [comment] 2021-04-10 11:06
Duplicate of #105

**Closed by richardolsson** 2021-04-10 11:06 UTC
Labels: duplicate
