### ISSUE TITLE
Created list from selection shows previous list's data

### ISSUE THREAD

**Issue by kaulfield23** [zetkin/app.zetkin.org#1571] opened 2023-10-04 09:50 UTC
**Please be as thorough as possible, but if you can't answer everything, please just submit what you have! Thank you!**

## Description
When I click check boxes in the list, I can create a new list that contains people I selected by using "Created list from selection". I expect to see selected people in a newly created list but somehow it is showing previous list's data.
Refreshing the page will only update the data in this list

## Steps to reproduce
1. Go to http://localhost:3000/organize/1/people/lists/42
2. Click check boxes of Zara and Nora
3. Click "Created list from selection"
4. Check the title and subtitles of the list. It is same as previous list which shouldn't be.
5. Edit the title to differentiate a created list from others
6. Don't refresh the page, instead, click on the people icon in the sidebar to go to `/people`
7. Find the list you created and click it

### Expected Behaviour
1. Right after creating a list
- Title should be **"New list"** as default. 
- Subtitles should display correct numbers

2. List
- Display selected people only.

### Actual Behaviour
1. Right after creating a list
- Title and subtitles are same as previous list.

2. List
- Display people of previous list

## Screenshots (if you have any)

https://github.com/zetkin/app.zetkin.org/assets/77925373/06b74270-a4af-4d6c-9eaa-5dfbfa36b642

**Comment by richardolsson** [comment] 2023-11-06 07:10
Not sure if this is still a problem after #1555, so first step for any volunteer is to check whether they can reproduce.

**Comment by avart** [comment] 2023-11-06 20:15
I could not reproduce this bug. After choosing Zara and Nora and clicking "Create list...", I reaced this screen - with a new list name and correct subtitles (or so I assume).
![Screenshot 2023-11-06 at 21 14 34](https://github.com/zetkin/app.zetkin.org/assets/967024/fe367a4f-7ddb-4ca9-9e0c-fb1e71fc99af)

**Comment by avart** [comment] 2023-11-06 20:18
After renaming the list, I could find it under the new name, and it contained the correct people.

**Comment by richardolsson** [comment] 2023-11-07 04:27
Thank you @avart for verifying! This will have likely been fixed by the #1555 refactor then. Closing! ✅

**Closed by richardolsson** 2023-11-07 04:27 UTC
Labels: 🐜 bug, 🚪 entry-level
